# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Estate
tagline:          ''
description:      ''
url:              http://www.hypergamy.estate
baseurl:          /

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/hypergamy/hypergamy.github.io

